name: RTD
version: '${project.version}'
main: net.levelmc.rtd.RTD
api-version: '1.12'
authors: [LevelMC]
description: a dice roll plugin
website: www.levelmc.net
commands:
  roll:
    description: Rolls the dice
    permission: rtd.roll
